export const ADDCART_SUCCESS='Bạn đã mua sản phẩm thành công'
export const UPDATE_ADDCART='Bạn đã cập nhật sản phẩm'
export const DELETE_ADDCART='Bạn đã xóa sản phẩm'
export const ADDCART_EMPTY='Chưa có sản phẩm nào trong giỏ hàng'
export const WELCOM_SHOP='Chào mừng bạn đến với shopping online'